export const PROMPTS = [
  "Something that looks like it's plotting revenge",
  "The weirdest snack combo in the room",
  "A shadow that could be a monster",
  "An object that screams midlife crisis",
  "A gadget from a low‑budget sci‑fi",
  "An item that would betray you in a fight",
  "The laziest camouflage attempt",
  "A souvenir from the apocalypse",
  "A villain's hobby",
  "Furniture for an alien",
  "The saddest balloon's final moments",
  "Your mood today, as an object",
  "Something that looks haunted",
  "The lamest magic trick prop",
  "A disguise nobody would take seriously",
  "A snack that belongs in a lab",
  "A portal to another dimension (interpret loosely)",
  "An everyday item feeling dramatic",
  "The ugliest mug you can find",
  "An item clearly having an identity crisis"
];